layout: stacked
style: light

repositories:
  - name: AnySearch
    description: A simple web interface, that allows users Search for countries and display its full details, and gets an amount in EUR to be converted into local currency for each country.
    web_url: https://dazzling-einstein-6ed7ba.netlify.com

  - name: DuckFeed
    description: The goal of the project is to create a web app that collects duck feeding partner in parks around the world.
    web_url: https://duckfeedapps.herokuapp.com/

  - name: Starwars
    description: Working with Starwars API.
    web_url: https://fervent-kepler-f69387.netlify.com/

  - name: QuickBuy
    description: Mini amazon for low volume internet sales. Built with React, Apollo GraphQL, GraphQL Yoga & Prisma
    web_url: https://github.com/temilolu/QuickBuy

  - name: OneBnB
    description: Enhancing local experiences through home sharing built in React.
    web_url: https://github.com/temilolu/oneBnB

  - name: OnePress
    description: Reverse engineering wordpress.com by building a similar full-stack version with Vue/firebase.
    web_url: https://github.com/temilolu/onepress

  

  

  

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

topics:
  - name: Express
    web_url: https://github.com/topics/express
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/express/express.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: Redux
    web_url: https://github.com/topics/redux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/redux/redux.png

  - name: GraphQL
    web_url: https://github.com/topics/graphql
    image_url: https://raw.githubusercontent.com/github/explore/5c058a388828bb5fde0bcafd4bc867b5bb3f26f3/topics/graphql/graphql.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/typescript/typescript.png
